package spot

// MinBidPrices contains the minimum bid prices for each server class
// Generated by probing the Rackspace Spot API
var MinBidPrices = map[string]float64{
	// Compute Heavy VS1
	"ch.vs1.medium-dfw": 0.001, "ch.vs1.medium-hkg": 0.001, "ch.vs1.medium-iad": 0.001,
	"ch.vs1.medium-lon": 0.001, "ch.vs1.medium-ord": 0.001, "ch.vs1.medium-syd": 0.001,
	"ch.vs1.large-dfw": 0.01, "ch.vs1.large-hkg": 0.01, "ch.vs1.large-iad": 0.005,
	"ch.vs1.large-lon": 0.02, "ch.vs1.large-ord": 0.01, "ch.vs1.large-syd": 0.01,
	"ch.vs1.xlarge-dfw": 0.015, "ch.vs1.xlarge-hkg": 0.015, "ch.vs1.xlarge-iad": 0.015,
	"ch.vs1.xlarge-lon": 0.1, "ch.vs1.xlarge-ord": 0.015, "ch.vs1.xlarge-syd": 0.015,
	"ch.vs1.2xlarge-dfw": 0.04, "ch.vs1.2xlarge-hkg": 0.04, "ch.vs1.2xlarge-iad": 0.04,
	"ch.vs1.2xlarge-lon": 0.04, "ch.vs1.2xlarge-ord": 0.04, "ch.vs1.2xlarge-syd": 0.04,
	// Compute Heavy VS2
	"ch.vs2.medium-dfw2": 0.01, "ch.vs2.medium-sjc": 0.01,
	"ch.vs2.large-dfw2": 0.03, "ch.vs2.large-sjc": 0.03,
	"ch.vs2.xlarge-dfw2": 0.141, "ch.vs2.xlarge-sjc": 0.27,
	// General Purpose VS1
	"gp.vs1.medium-dfw": 0.001, "gp.vs1.medium-hkg": 0.001, "gp.vs1.medium-iad": 0.001,
	"gp.vs1.medium-lon": 0.004, "gp.vs1.medium-ord": 0.005, "gp.vs1.medium-syd": 0.001,
	"gp.vs1.large-dfw": 0.003, "gp.vs1.large-hkg": 0.002, "gp.vs1.large-iad": 0.002,
	"gp.vs1.large-lon": 0.02, "gp.vs1.large-ord": 0.003, "gp.vs1.large-syd": 0.01,
	"gp.vs1.xlarge-dfw": 0.005, "gp.vs1.xlarge-hkg": 0.005, "gp.vs1.xlarge-iad": 0.03,
	"gp.vs1.xlarge-lon": 0.03, "gp.vs1.xlarge-ord": 0.005, "gp.vs1.xlarge-syd": 0.02,
	"gp.vs1.2xlarge-dfw": 0.04, "gp.vs1.2xlarge-hkg": 0.04, "gp.vs1.2xlarge-iad": 0.04,
	"gp.vs1.2xlarge-lon": 0.04, "gp.vs1.2xlarge-ord": 0.04, "gp.vs1.2xlarge-syd": 0.04,
	// General Purpose VS2
	"gp.vs2.medium-dfw2": 0.01, "gp.vs2.medium-sjc": 0.01,
	"gp.vs2.large-dfw2": 0.04, "gp.vs2.large-sjc": 0.04,
	"gp.vs2.xlarge-dfw2": 0.08, "gp.vs2.xlarge-sjc": 0.08,
	"gp.vs2.2xlarge-dfw2": 0.04, "gp.vs2.2xlarge-sjc": 0.04,
	// Memory Heavy VS1
	"mh.vs1.medium-dfw": 0.01, "mh.vs1.medium-hkg": 0.01, "mh.vs1.medium-iad": 0.01,
	"mh.vs1.medium-lon": 0.002, "mh.vs1.medium-ord": 0.01, "mh.vs1.medium-syd": 0.01,
	"mh.vs1.large-dfw": 0.005, "mh.vs1.large-hkg": 0.005, "mh.vs1.large-iad": 0.005,
	"mh.vs1.large-lon": 0.05, "mh.vs1.large-ord": 0.005, "mh.vs1.large-syd": 0.005,
	"mh.vs1.xlarge-dfw": 0.01, "mh.vs1.xlarge-hkg": 0.01, "mh.vs1.xlarge-iad": 0.01,
	"mh.vs1.xlarge-lon": 0.01, "mh.vs1.xlarge-ord": 0.01, "mh.vs1.xlarge-syd": 0.01,
	"mh.vs1.2xlarge-dfw": 0.04, "mh.vs1.2xlarge-hkg": 0.04, "mh.vs1.2xlarge-iad": 0.04,
	"mh.vs1.2xlarge-lon": 0.04, "mh.vs1.2xlarge-ord": 0.04, "mh.vs1.2xlarge-syd": 0.04,
	// Memory Heavy VS2
	"mh.vs2.medium-dfw2": 0.03, "mh.vs2.medium-sjc": 0.03,
	"mh.vs2.large-dfw2": 0.06, "mh.vs2.large-sjc": 0.06,
	"mh.vs2.xlarge-dfw2": 0.12, "mh.vs2.xlarge-sjc": 0.12,
	// GPU
	"gpu.vs2.xlargeplusplus-sjc": 0.15,
	"gpu.vs2.megaxlarge-sjc":     2.69,
}

// GetMinBidPrice returns the minimum bid price for a server class
func GetMinBidPrice(serverClass string) float64 {
	if min, ok := MinBidPrices[serverClass]; ok {
		return min
	}
	// Default fallback for unknown server classes
	return 0.01
}
